import type {
  Child,
  Alert,
  ActivityItem,
  GeofenceZone,
  HistoryLog,
} from "@/types";

export const mockChildren: Child[] = [
  {
    id: "child-1",
    name: "Emma Johnson",
    age: 9,
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=Emma",
    deviceName: "Emma's iPhone",
    batteryLevel: 78,
    isOnline: true,
    lastSeen: new Date(Date.now() - 5 * 60000).toISOString(),
    location: {
      lat: 40.7128,
      lng: -74.006,
      address: "Lincoln Elementary School, New York, NY",
      timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    },
    safeStatus: "safe",
    school: "Lincoln Elementary",
    grade: "3rd Grade",
  },
  {
    id: "child-2",
    name: "Lucas Johnson",
    age: 12,
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=Lucas",
    deviceName: "Lucas's Android",
    batteryLevel: 23,
    isOnline: true,
    lastSeen: new Date(Date.now() - 12 * 60000).toISOString(),
    location: {
      lat: 40.7282,
      lng: -73.9942,
      address: "Washington Middle School, New York, NY",
      timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
    },
    safeStatus: "warning",
    school: "Washington Middle School",
    grade: "7th Grade",
  },
  {
    id: "child-3",
    name: "Sophie Johnson",
    age: 7,
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=Sophie",
    deviceName: "Sophie's Tablet",
    batteryLevel: 91,
    isOnline: false,
    lastSeen: new Date(Date.now() - 2 * 3600000).toISOString(),
    location: {
      lat: 40.7549,
      lng: -73.984,
      address: "Home, 123 Maple Street, New York, NY",
      timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    },
    safeStatus: "safe",
    school: "Maple Street Primary",
    grade: "1st Grade",
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "alert-1",
    childId: "child-2",
    childName: "Lucas Johnson",
    type: "geofence",
    severity: "high",
    title: "Left Safe Zone",
    description: "Lucas has left the school geofence boundary.",
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    isRead: false,
    location: "Washington Middle School",
  },
  {
    id: "alert-2",
    childId: "child-2",
    childName: "Lucas Johnson",
    type: "battery",
    severity: "medium",
    title: "Low Battery Warning",
    description: "Lucas's device battery is at 23%. Please charge soon.",
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
    isRead: false,
  },
  {
    id: "alert-3",
    childId: "child-1",
    childName: "Emma Johnson",
    type: "location",
    severity: "low",
    title: "Arrived at School",
    description: "Emma has arrived at Lincoln Elementary School.",
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    isRead: true,
    location: "Lincoln Elementary School",
  },
  {
    id: "alert-4",
    childId: "child-3",
    childName: "Sophie Johnson",
    type: "device",
    severity: "low",
    title: "Device Offline",
    description: "Sophie's tablet has gone offline.",
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    isRead: true,
  },
  {
    id: "alert-5",
    childId: "child-1",
    childName: "Emma Johnson",
    type: "app_usage",
    severity: "medium",
    title: "Restricted App Detected",
    description: "Emma tried to open a restricted application.",
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    isRead: true,
  },
  {
    id: "alert-6",
    childId: "child-2",
    childName: "Lucas Johnson",
    type: "sos",
    severity: "critical",
    title: "SOS Button Pressed",
    description: "Lucas pressed the SOS button. Immediate attention required.",
    timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
    isRead: true,
    location: "42nd Street, New York, NY",
  },
];

export const mockActivities: ActivityItem[] = [
  {
    id: "act-1",
    childId: "child-1",
    type: "location_update",
    title: "Location Updated",
    description: "Emma's location updated to Lincoln Elementary School",
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    location: "Lincoln Elementary School",
  },
  {
    id: "act-2",
    childId: "child-1",
    type: "geofence_enter",
    title: "Entered Safe Zone",
    description: "Emma entered the School safe zone",
    timestamp: new Date(Date.now() - 48 * 60000).toISOString(),
    location: "Lincoln Elementary School",
  },
  {
    id: "act-3",
    childId: "child-2",
    type: "geofence_exit",
    title: "Left Safe Zone",
    description: "Lucas left the School safe zone boundary",
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    location: "Washington Middle School area",
  },
  {
    id: "act-4",
    childId: "child-2",
    type: "device_activity",
    title: "Device Unlocked",
    description: "Lucas unlocked his Android device",
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: "act-5",
    childId: "child-3",
    type: "device_activity",
    title: "Device Offline",
    description: "Sophie's tablet went offline",
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "act-6",
    childId: "child-1",
    type: "app_usage",
    title: "App Used",
    description: "Emma opened the Math Learning app",
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
  },
];

export const mockGeofences: GeofenceZone[] = [
  {
    id: "geo-1",
    name: "Home",
    type: "home",
    radius: 200,
    isActive: true,
    lat: 40.7549,
    lng: -73.984,
    alertOnEnter: false,
    alertOnExit: true,
    color: "#DAEFB3",
  },
  {
    id: "geo-2",
    name: "Lincoln Elementary",
    type: "school",
    radius: 300,
    isActive: true,
    lat: 40.7128,
    lng: -74.006,
    alertOnEnter: true,
    alertOnExit: true,
    color: "#EA9E8D",
  },
  {
    id: "geo-3",
    name: "Washington Middle School",
    type: "school",
    radius: 350,
    isActive: true,
    lat: 40.7282,
    lng: -73.9942,
    alertOnEnter: true,
    alertOnExit: true,
    color: "#EA9E8D",
  },
  {
    id: "geo-4",
    name: "Grandma's House",
    type: "custom",
    radius: 150,
    isActive: false,
    lat: 40.7589,
    lng: -73.9851,
    alertOnEnter: true,
    alertOnExit: false,
    color: "#D64550",
  },
];

export const mockHistoryLogs: HistoryLog[] = [
  {
    id: "log-1",
    childId: "child-1",
    childName: "Emma",
    event: "Arrived at Lincoln Elementary",
    location: "Lincoln Elementary School, NY",
    timestamp: new Date(Date.now() - 48 * 60000).toISOString(),
    type: "geofence_enter",
  },
  {
    id: "log-2",
    childId: "child-2",
    childName: "Lucas",
    event: "Left School Zone",
    location: "Washington Middle School, NY",
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    type: "geofence_exit",
  },
  {
    id: "log-3",
    childId: "child-1",
    childName: "Emma",
    event: "Location Check-in",
    location: "Lincoln Elementary School, NY",
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    type: "location_update",
  },
  {
    id: "log-4",
    childId: "child-3",
    childName: "Sophie",
    event: "Device Offline",
    location: "Home, Maple Street, NY",
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    type: "device_activity",
  },
  {
    id: "log-5",
    childId: "child-2",
    childName: "Lucas",
    event: "SOS Triggered",
    location: "42nd Street, New York, NY",
    timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
    type: "sos_trigger",
  },
  {
    id: "log-6",
    childId: "child-1",
    childName: "Emma",
    event: "App Usage Detected",
    location: "Lincoln Elementary School, NY",
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    type: "app_usage",
  },
  {
    id: "log-7",
    childId: "child-2",
    childName: "Lucas",
    event: "Returned to School Zone",
    location: "Washington Middle School, NY",
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    type: "geofence_enter",
  },
  {
    id: "log-8",
    childId: "child-3",
    childName: "Sophie",
    event: "Device Online",
    location: "Home, Maple Street, NY",
    timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
    type: "device_activity",
  },
];
